server:
  port: 8180
  servlet:
    context-path: /app

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver